const app = document.getElementById('app');
const stages = {
  1:{name:'Laluan Kenal Alam', objects:[['cat','🐱',34,34,'Haiwan'],['chicken','🐔',67,22,'Haiwan'],['flower','🌺',73,43,'Tumbuhan'],['grass','🌿',45,62,'Tumbuhan']]},
  2:{name:'Hutan Ciri-Ciri', objects:[['cat','🐱',26,33,'ada kaki'],['fish','🐟',43,28,'ada sirip'],['flower','🌼',76,42,'ada daun'],['banana','🌴',66,57,'ada batang']]},
};
let state={screen:'home',stage:1,score:0,lives:3,x:50,y:55,asked:{},sound:true,two:false,turn:0,players:[{name:'Pemain 1',score:0},{name:'Pemain 2',score:0}]};
const btn=(t,c,fn)=>`<button class="btn ${c}" onclick="${fn}">${t}</button>`;
function render(){({home,game,mission,chat,leader,final,twoSetup,twoResult}[state.screen]||home)()}
function base(cls='forest'){app.innerHTML=`<section class="screen ${cls}"><div class="path"></div></section>`;return app.firstChild}
function home(){const s=base();s.innerHTML+=`<div class="title-board wood"><h1>Misi<br>Alam Ceria</h1><p>Sains Sosial MBPK</p></div><div class="home-grid"><div><div class="bubble">Jom bertualang bersama <b>Budi si Burung!</b></div><div class="mascot" title="Budi si Burung">🐦</div></div><div class="menu-buttons">${btn('🐼 Main Sendiri','green','start(false)')}${btn('👥 Main Dengan Kawan','blue','showTwoSetup()')}${btn('💬 Tanya Budi','purple','go("chat")')}${btn('❔ Cara Main','orange','alert("Gerakkan watak, dekatkan diri kepada objek, kemudian jawab soalan. Kumpul mata dan lencana!")')}${btn('🗺️ Peta Misi','blue','go("mission")')}${btn('🏆 Papan Pendahuluan','orange','go("leader")')}</div></div><button class="btn blue sound" onclick="toggleSound()">${state.sound?'🔊':'🔇'}</button>`}
function hud(){return `<div class="hud"><div class="wood pill"><b>Stage ${state.stage}</b><br>${stageName()}</div><div class="stats"><span class="pill">⭐ Skor: ${score()}</span><span class="pill">❤️ ${state.lives}</span>${state.two?`<span class="pill">Giliran: ${state.players[state.turn].name}</span>`:''}<button class="btn blue" onclick="go('home')">☰</button></div></div>`}
function game(){const s=base('');const cfg=stages[state.stage]||stages[1];s.innerHTML=`<div class="map"></div>${hud()}<div class="player" style="left:${state.x}%;top:${state.y}%">🧒</div>${cfg.objects.map(o=>`<button class="obj" style="left:${o[2]}%;top:${o[3]}%" onclick="ask('${o[0]}')">${o[1]}</button>`).join('')}<div class="dpad"><span></span><button onpointerdown="move(0,-6)">▲</button><span></span><button onpointerdown="move(-6,0)">◀</button><span></span><button onpointerdown="move(6,0)">▶</button><span></span><button onpointerdown="move(0,6)">▼</button><span></span></div><div class="mini"></div>`;checkNear()}
function popup(o){const choices=state.stage===1?['Haiwan','Tumbuhan']:['ada kaki','ada sirip','ada daun','ada batang'];app.firstChild.innerHTML+=`<div class="modal"><div class="card"><button class="btn red close" onclick="render()">×</button><div class="wood pill" style="font-size:30px">SOALAN</div><div class="icon-big">${o[1]}</div><h2>${state.stage===1?'Ini haiwan atau tumbuhan?':'Pilih ciri yang betul.'}</h2><div class="answer-row">${choices.map((x,i)=>btn(x,['green','blue','orange','purple'][i%4],`answer('${o[0]}','${x}')`)).join('')}</div><p id="feedback" class="feedback"></p></div></div>`}
function ask(id){const o=(stages[state.stage]||stages[1]).objects.find(x=>x[0]===id); if(o) popup(o)}
function answer(id,val){const o=(stages[state.stage]||stages[1]).objects.find(x=>x[0]===id), f=document.getElementById('feedback'); if(val===o[4]){state.score+=10;if(state.two)state.players[state.turn].score+=10;state.asked[`${state.stage}-${id}`]=true;f.textContent='Bagus! Jawapan kamu betul.';saveScore();setTimeout(nextStep,800)}else{state.lives=Math.max(0,state.lives-1);f.textContent='Tidak mengapa. Cuba lagi.'}}
function nextStep(){if(Object.keys(state.asked).filter(k=>k.startsWith(state.stage+'-')).length>=4){if(state.stage<3){state.stage++;state.x=50;state.y=55;if(state.stage===3) stage3(); else render()}else finish()}else render()}
function stage3(){state.screen='stage3';const s=base('');s.innerHTML=`<div class="map"></div>${hud()}<div class="zones"><div class="zone" onclick="zone('Haiwan')">ZON HAIWAN<br>🐾</div><div class="zone" onclick="zone('Tumbuhan')">ZON TUMBUHAN<br>🌱</div></div><div class="player" style="left:48%;top:58%">🧒</div><div class="items">${['🐰','🐦','🌻','🌳'].map((e,i)=>`<button class="pick" onclick="pick(${i})">${e}</button>`).join('')}</div>`}
let selected=0, zoneItems=[['🐰','Haiwan'],['🐦','Haiwan'],['🌻','Tumbuhan'],['🌳','Tumbuhan']];function pick(i){selected=i;document.querySelectorAll('.pick').forEach((b,n)=>b.style.outline=n===i?'6px solid yellow':'0')}function zone(z){if(zoneItems[selected]&&zoneItems[selected][1]===z){state.score+=10;if(state.two)state.players[state.turn].score+=10;zoneItems.splice(selected,1);selected=0;saveScore(); if(!zoneItems.length)finish(); else stage3()}else alert('Tidak mengapa. Cuba lagi.')}
function mission(){const s=base('forest');s.innerHTML+=`<div class="mission"><div class="wood pill" style="display:inline-block;font-size:30px">PETA MISI</div><div class="nodes">${['Laluan\nKenal Alam','Hutan\nCiri-Ciri','Pondok\nSusun Alam','Taman\nCeria\n(FINAL)'].map((n,i)=>`<div class="node ${['green','blue','orange','purple'][i]}"><b>${i+1}</b><br>${n.replaceAll('\n','<br>')}</div>${i<3?'<div class="arrow">➜</div>':''}`).join('')}</div>${btn('Menu Utama','blue','go("home")')}</div>`}
function chat(){const s=base('forest');s.innerHTML+=`<div class="chat"><div><div class="mascot">🐦</div></div><div class="chatbox"><h1>Tanya Budi</h1><div id="msgs"><div class="msg budi">Hai! Tanya Budi tentang haiwan dan tumbuhan.</div></div><div class="inputrow"><input id="q" placeholder="Tanya soalan di sini..." onkeydown="if(event.key==='Enter')budi()"><button class="btn green" onclick="budi()">➤</button></div>${btn('Menu Utama','blue','go("home")')}</div></div>`}
function budi(){const q=document.getElementById('q'),m=document.getElementById('msgs');let a='Cuba lihat ciri mudah seperti kaki, sirip, daun, batang dan akar.';if(q.value.includes('haiwan'))a='Haiwan biasanya boleh bergerak dan ada kaki, sayap atau sirip.';if(q.value.includes('tumbuhan'))a='Tumbuhan biasanya ada daun, batang dan akar.';if(q.value.includes('beza'))a='Haiwan boleh bergerak sendiri. Tumbuhan tumbuh di tanah dan ada daun, batang atau akar.';m.innerHTML+=`<div class="msg me">${q.value}</div><div class="msg budi">${a}</div>`;q.value=''}
function leader(){const data=JSON.parse(localStorage.misiAlamScores||'[]');const rows=[['🥇','Aiman',90],['🥈','Siti',80],['🥉','Danial',70],['4','Sara',60],...data].sort((a,b)=>b[2]-a[2]).slice(0,6);const s=base('forest');s.innerHTML+=`<div class="leader wood"><h1>Papan Pendahuluan</h1>${rows.map(r=>`<div class="rank"><span>${r[0]}</span><span>${r[1]}</span><span>${r[2]} mata</span></div>`).join('')}${btn('Menu Utama','blue','go("home")')}</div>`}
function final(){let b=score()>=90?'Lencana Juara Alam':score()>=60?'Lencana Penjaga Alam':'Lencana Pemula Alam';const s=base('forest');s.innerHTML+=`<div class="final"><h1>TAHNIAH!</h1><h2>Kamu berjaya menamatkan semua misi!</h2><div class="badge">🏅</div><h2>${b}</h2><h1>${score()} mata</h1>${btn('Main Semula','green','start(false)')}${btn('Menu Utama','blue','go("home")')}${btn('Papan Skor','orange','go("leader")')}</div>`}
function twoSetup(){const s=base('forest');s.innerHTML+=`<div class="name-form"><h1>Mod Dua Pemain</h1><input id="p1" placeholder="Nama Pemain 1"><input id="p2" placeholder="Nama Pemain 2">${btn('Mula VS Mesra','green','startTwo()')}${btn('Menu Utama','blue','go("home")')}</div>`}
function twoResult(){const s=base('forest');s.innerHTML+=`<div class="vs"><div class="player-card"><h2>${state.players[0].name}</h2><p>Skor</p><h1>${state.players[0].score}</h1></div><div class="vsmark">VS</div><div class="player-card" style="border-color:#d95035;background:#ffe0cf"><h2>${state.players[1].name}</h2><p>Skor</p><h1>${state.players[1].score}</h1></div></div><p class="pill" style="position:absolute;left:50%;bottom:70px;transform:translateX(-50%);z-index:3">Main secara bergilir. Semoga berjaya!</p>`}
function move(dx,dy){state.x=Math.max(3,Math.min(91,state.x+dx));state.y=Math.max(12,Math.min(82,state.y+dy));render()}function checkNear(){(stages[state.stage]||{objects:[]}).objects.forEach(o=>{if(!state.asked[`${state.stage}-${o[0]}`]&&Math.hypot(state.x-o[2],state.y-o[3])<8) setTimeout(()=>ask(o[0]),120)})}function score(){return state.two?state.players[state.turn].score:state.score}function stageName(){return state.stage===3?'Pondok Susun Alam':(stages[state.stage]||stages[1]).name}function go(s){state.screen=s;render()}function showTwoSetup(){state.screen='twoSetup';render()}function start(two){state={...state,screen:'game',stage:1,score:0,lives:3,x:50,y:55,asked:{},two};render()}function startTwo(){state.players=[{name:document.getElementById('p1').value||'Pemain 1',score:0},{name:document.getElementById('p2').value||'Pemain 2',score:0}];state.turn=0;start(true)}function finish(){if(state.two&&state.turn===0){state.turn=1;state.stage=1;state.x=50;state.y=55;state.asked={};state.screen='game';render()}else{saveScore();state.screen=state.two?'twoResult':'final';render()}}function saveScore(){localStorage.misiAlamScores=JSON.stringify([['⭐','Pemain',state.score],...(JSON.parse(localStorage.misiAlamScores||'[]'))].slice(0,8))}function toggleSound(){state.sound=!state.sound;render()}
document.addEventListener('keydown',e=>{if(state.screen==='game'){if(e.key==='ArrowUp')move(0,-4);if(e.key==='ArrowDown')move(0,4);if(e.key==='ArrowLeft')move(-4,0);if(e.key==='ArrowRight')move(4,0)}});render();
